trigger: 
  - master

variables:
  dockerImageName: adarsh011/adarsh-app
  azureWebAppName: adu-java-webapp
  azureResourceGroup: OCEAN

pool:
  name: "Adarsh-CI-CD"

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: MavenBuild
    displayName: 'Maven Package'
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package'

    - task: CopyFiles@2
      inputs:
        SourceFolder: 'Amazon-Web/target'  
        Contents: '*.war'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'drop'

- stage: Docker
  displayName: 'Docker Build and Push'
  dependsOn: Build
  jobs:
  - job: DockerBuildPush
    displayName: 'Build & Push Docker Image'
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        artifactName: 'drop'
        targetPath: '$(Build.SourcesDirectory)/docker-context'

    - task: CopyFiles@2
      displayName: 'Prepare WAR for Docker build'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/docker-context'
        Contents: '*.war'
        TargetFolder: '$(Build.SourcesDirectory)'

    - script: |
        echo "Listing files in Docker build context:"
        dir  $(Build.SourcesDirectory)\Amazon-Web\target
      displayName: 'Verify WAR in build context'

    - task: Docker@2
      inputs:
        command: 'login'
        containerRegistry: 'adarsh-dhub'

    - task: Docker@2
      inputs:
        command: 'buildAndPush'
        repository: '$(dockerImageName)'
        dockerfile: 'Dockerfile'
        buildContext: '$(Build.SourcesDirectory)'
        tags: |
          latest
          $(Build.BuildId)

- stage: Deploy
  displayName: 'Deploy to Azure Web App'
  dependsOn: Docker
  jobs:
  - deployment: DeployWebApp
    displayName: 'Deploy Container to Azure'
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: 'adarsh-azure'
              appName: '$(azureWebAppName)'
              containers: '$(dockerImageName):latest'

